/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactMan: typeof import('./src/components/contactMan/index.vue')['default']
    'ContactMan.vue': typeof import('./src/components/contactMan.vue/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Morebox: typeof import('./src/components/header/components/morebox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanFiled: typeof import('vant/es')['Filed']
    VanForm: typeof import('vant/es')['Form']
    VanInput: typeof import('vant/es')['Input']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VantBtn: typeof import('vant/es')['tBtn']
    VantButton: typeof import('vant/es')['tButton']
  }
}
